spring:
  application:
    name: banco-com-jwt-e-security
  datasource:
    url: jdbc:postgresql://localhost:5432/security
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQLDialect